# Generated by Django 5.2.8 on 2025-11-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Operativa', 'Operativa'), ('En mantenimiento', 'En mantenimiento'), ('No operativa', 'No operativa')], default='Operativa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidad', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Mantencion',
            fields=[
                ('id_mantencion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('id_maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.maquina')),
                ('id_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantencion.responsable')),
            ],
        ),
    ]
